"""init db

Revision ID: 4aff17288528
Revises: 
Create Date: 2023-09-17 11:19:00.062804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aff17288528'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Person',
    sa.Column('snils', sa.String(length=14), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('patronimic', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('snils')
    )
    op.create_table('SocialGroup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Card',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('bank_card_id', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.String(length=14), nullable=True),
    sa.Column('emission_date', sa.DateTime(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Person.snils'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PersonSocialGroup',
    sa.Column('person_snils', sa.String(length=14), nullable=True),
    sa.Column('social_group_id', sa.Uuid(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person_snils'], ['Person.snils'], ),
    sa.ForeignKeyConstraint(['social_group_id'], ['SocialGroup.id'], )
    )
    op.create_table('Complain',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.String(length=16), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Complain')
    op.drop_table('PersonSocialGroup')
    op.drop_table('Card')
    op.drop_table('SocialGroup')
    op.drop_table('Person')
    # ### end Alembic commands ###
